### PR TITLE
Swap to SDL2

### PR DESCRIPTION
**Pull request by Kethku**
This is a decidedly work in progress PR which swaps sdl2 in for winit. While trying to make neovide in a cross platform way, I was constantly running into inconsistencies and bugs between the different versions.

You noticed some of them in the errors with 0.5, but there were deeper ones such as the bad keyboard input support, buggy redraw logic on windows etc.

So I did an experiment where I swapped to sdl2 and basically all of those issues went away. I only ended up updating the renderer logic, but I don't think it would be that hard to update the app logic... it would definitely be a breaking change though.

Further, there were a number of places where I unwrapped results so as to not deal with differing Result types. So there is a bunch of cleanup that would be required.

Mostly I'm just creating this PR to make sure you are aware of the core issues, and a possible solution. Maybe with some thought we could make the API window system agnostic so that the user could pick? I'm not sure what that would look like, but its kinda a shame that the Rust first solution is so buggy.

### CODE REVIEW

**Comment by Kethku** [comment]
Details wise, I'm not happy with my recreation of logical vs physical sizes and the coopting of the type for positions as well.

However there was a big improvement in the vulkan extension and surface creation since the sdl2 library does that for you. The window management code which was gnarly and reimplemented per platform turned into a tiny file which just managed raw handles.

Dpi support was the biggest differential between winit and sdl2. Winit has very good support while sdl2 is somewhat lacking on windows. I got around this by checking the reported dpi vs the default dpi per platform, but I think it could be improved especially since ideally the window would automatically change size to preserve the logical size rather than just reporting a change in window size.

And just to reiterate, the code was quick and dirty since I wanted to unblock folks in neovide. If and when an integration plan is arrived at, I will work to make it better

**Comment by aclysma** [comment]
I’ll need to look at this in more detail later and maybe even give sdl2 a try for myself. My very first thought is that it should be possible to use a lot of the renderer code with both winit and sdl2.

The app portion should probably be in a separate crate from the renderer anyways. For the app layer on one hand I’d like this to stay on winit so as to keep an easy, mostly rust way to get something on the screen. On the other hand, there are show stopping bugs in winit and it doesn’t feel like they will be fixed soon. “Not working” isn’t friendly to beginners either.

That said, there’s the option of having an “app” crate for both SDL and winit. (Not an abstraction, but a winit-flavored version and an SDL-flavored version that wires things up and exposes winit/SDL interfaces to the end user.)

I agree with you, I’d really like to keep within the rust ecosystem by using winit, but it’s not usable in its current shape for real, shipping code.

**Comment by aclysma** [comment]
I fetched your branch and pushed it into skulpin under a branch. I updated the renderer example. I like how it feels so far.. I did notice that resizing the window makes the rendering pause. For games I don't think it's a big deal, but for general windowing stuff it's not ideal. If we have a good way of using the same code for both SDL2 and winit backends, that could be a good solution. Would let people stay within the rust ecosystem (and hopefully winit will improve!), but also allow using SDL2 which is more stable.

**Comment by Kethku** [comment]
I have looked into that. I think there is a workaround which handles window resize events on a separate thread. I believe the issue is that on windows resize events block the event loop but also on windows, handling events must be on the main thread which is a conflict.

https://stackoverflow.com/a/50858339

This stackoverflow answer describes a way to listen to resize events in a different way which could fix the problem. I haven't been able to dig in to figure it out yet though.

**Comment by Kethku** [comment]
Also you should be aware, that on macos the mailbox rendering option causes the app to crash occasionally. I have no idea how vulkan works to be honest, and found that the issue goes away once I switched to immediate rendering.

image

Jon reported the issue and found it was in the renderer code:

image

But again, I'm really unfamiliar with how it works under the covers, so my solution was a stab in the dark that happened to fix it in neovide, but will require more detailed investigation

**Comment by aclysma** [comment]
I think PresentMode::Fifo is the most appropriate present mode for your application. This locks you to vsync and avoids screen tearing. Immediate could cause screen tearing. It’s not intended for use on a desktop OS. All my macOS testing has been on a laptop with iGPU, it is not possible to run it in mailbox mode. Do you know what GPU is getting this crash?

The present_index rotates through the N buffers that are part of the swapchain. The swapchain is returning the index it’s on, and it seems like the swapchain has more images than we requested, which is bad because we allocate some resources per buffer and are trying to fetch them by that index.

I noticed that the skulpin call to vk::SwapchainCreateInfoKHR::builder sets a min image count but not a max, and the image count it returns is the minimum. If the swapchain allocates more than the minimum, I could see how this crash might happen.

We could try setting a max, or determining how many images the swapchain code chose to allocate and populate SwapchainInfo with that instead of the minimum we requested.

**Comment by Kethku** [comment]
Setting a max, or allowing the downstream app to configure it seems reasonable to me. The reason I bring it up here is that this issue only showed up in the sdl2 branch and worked fine in the current master. I don't really understand how my changes could have made any difference in this circumstance other than maybe the sdl2 extensions or surface creation is causing this...

**Comment by aclysma** [comment]
I pushed a commit that might fix the issue you mentioned. It looks like a legitimate bug that should be fixed even if it is only happening when combined with SDL. https://github.com/aclysma/skulpin/commit/b36d8ca5ee752b2a5dfda94998fe71de3a3e22ad

**Comment by Kethku** [comment]
Closing as it makes more sense to just upstream the windows specific dpi fixes

**Pull request closed without merging**
