### PR TITLE
Fix vulkan crashes

### PR DESCRIPTION
**Pull request by mmcjimsey26**
Fixes several issues related to the Vulkan rendering and backend skia textures. Also updates skia version to latest.

Solves #111.

### CODE REVIEW

**Comment by aclysma** [comment]
Looks good, I take it the fix is to just remove the hack and update to a more recent version of skia? I'm guessing the other changes are just to match upstream breaking API changes in skia.

**Comment by mmcjimsey26** [comment]
The only change that was unrelated (as far as I could tell) to the skia version was the call to `std::mem::transmute`, which was causing a segfault even before skia was updated (`free(): invalid pointer`). 

The function `ColorType::n32()` was deprecated in skia version 0.51.0.

**Comment by DorianRudolph** [comment]
I just tried out this code and still got a `free(): invalid pointer` crash. [log.txt](https://github.com/aclysma/skulpin/files/10345440/log.txt)

**Comment by DorianRudolph** [comment]
It seems my issue is a little bit different than the original. When debugging, It actually renders the first frame correctly, then the window is resized by my tiling window manager (sway), which causes a `rebuild_swapchain` in rafx, which calls `swapchain_destroyed`, where then `*self.skia_surface = None;` crashes.

Call stack:
```
___lldb_unnamed_symbol3503 (@___lldb_unnamed_symbol3503:77)
raise (@raise:10)
abort (@abort:50)
___lldb_unnamed_symbol3401 (@___lldb_unnamed_symbol3401:181)
___lldb_unnamed_symbol3567 (@___lldb_unnamed_symbol3567:11)
___lldb_unnamed_symbol3591 (@___lldb_unnamed_symbol3591:293)
__libc_free (@__libc_free:31)
skia_safe::gpu::backend_surface::<impl skia_safe::prelude::NativeDrop for skia_bindings::bindings::GrBackendTexture>::drop (/home/dorian/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-safe-0.57.0/src/gpu/backend_surface.rs:179)
<skia_safe::prelude::Handle<N> as core::ops::drop::Drop>::drop (/home/dorian/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-safe-0.57.0/src/prelude.rs:342)
core::ptr::drop_in_place<skia_safe::prelude::Handle<skia_bindings::bindings::GrBackendTexture>> (@core::ptr::drop_in_place<skia_safe::prelude::Handle<skia_bindings::bindings::GrBackendTexture>>:6)
core::ptr::drop_in_place<skulpin_renderer::skia_support::VkSkiaSurface> (@core::ptr::drop_in_place<skulpin_renderer::skia_support::VkSkiaSurface>:55)
core::ptr::drop_in_place<core::option::Option<skulpin_renderer::skia_support::VkSkiaSurface>> (@core::ptr::drop_in_place<core::option::Option<skulpin_renderer::skia_support::VkSkiaSurface>>:18)
<skulpin_renderer::renderer::SwapchainEventListener as rafx_api::extra::swapchain_helper::RafxSwapchainEventListener>::swapchain_destroyed (/home/dorian/projects/whiteboardcx/skulpin/skulpin-renderer/src/renderer.rs:134)
rafx_api::extra::swapchain_helper::RafxSwapchainHelper::rebuild_swapchain (/home/dorian/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.14/src/extra/swapchain_helper.rs:492)
rafx_api::extra::swapchain_helper::RafxSwapchainHelper::acquire_next_image (/home/dorian/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.14/src/extra/swapchain_helper.rs:411)
skulpin_renderer::renderer::Renderer::draw (/home/dorian/projects/whiteboardcx/skulpin/skulpin-renderer/src/renderer.rs:241)
skulpin_app_winit::app::App::run::{{closure}} (/home/dorian/projects/whiteboardcx/skulpin/skulpin-app-winit/src/app.rs:287)
winit::platform_impl::platform::sticky_exit_callback (/home/dorian/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:746)
winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return (/home/dorian/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/wayland/event_loop/mod.rs:376)
winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run (/home/dorian/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/wayland/event_loop/mod.rs:191)
```

Update 1: Your change to the transmute function does not seem to make a difference for me:

```rs
    pub fn get_image_from_skia_texture(texture: &skia_safe::gpu::BackendTexture) -> vk::Image {
        unsafe { 
            let image1 : vk::Image = std::mem::transmute(texture.vulkan_image_info().unwrap().image);
            let image2 : vk::Image = std::mem::transmute(texture.vulkan_image_info().unwrap().image.as_ref().unwrap());
            println!("get_image_from_skia_texture {image1:?} {image2:?}");
            image2
        }
    }
```
outputs
```
get_image_from_skia_texture 0x5567bdae0ba0 0x5567bdae0ba0
```

Update 2: The app seems to run fine for multiple frames until resizing.

Update 3: Meanwhile, I updated my Arch Linux and now apparently the winit version and sway are no longer compatible, so I'm running on X11, and a slightly different error when resizing: `munmap_chunk(): invalid pointer`.

Update 4: Did some further debugging. LD_PRELOADed the malloc and free. The final free causing the crash seems to be the address in `texture.fLabel[0]`

Update 5: It already breaks when freeing the texture inside `VkSkiaSurface::new`. I added the following code
```rs
        {
            let texture = surface
                .get_backend_texture(skia_safe::surface::BackendHandleAccess::FlushRead)
                .unwrap();
            println!("first texture:\n{texture:?}");
        } // CRASH HERE
        let texture = surface
            .get_backend_texture(skia_safe::surface::BackendHandleAccess::FlushRead)
            .unwrap();
        println!("second texture:\n{texture:?}");
```

Update 6: I think the issue might be the fLabel string. It is not generally possible to memcopy `std::string`. The reason for this is SSO (small string optimization): When the string is SSO'd, it contains its own address, which the destructor uses to determine if the string is SSO'd and does not actually need to be freed.
Relevant code from basic_string.h:
```c++
      _GLIBCXX20_CONSTEXPR
      bool
      _M_is_local() const
      { return _M_data() == _M_local_data(); }
      void
      _M_dispose()
      {
	if (!_M_is_local())
	  _M_destroy(_M_allocated_capacity);
      }
      ~basic_string()
      { _M_dispose(); }

```
So if we just memcpy a string on the stack, the destructor of the copied string will try to free a stack address which and crashes. I have no idea how this would have ever worked, so maybe I'm missing something. Maybe optimization removed copies previously? Very strange.

Well it seems like this issue needs to be fixed upstream in skia-safe.

**Comment by aclysma** [comment]
Sorry, I forgot to merge this. Thanks for tracking it down!

**Pull request merged**
