### PR TITLE
Patch winit

### PR DESCRIPTION
**Pull request by Pytal**

### CODE REVIEW

**Comment by uhuntu** [comment]
@Pytal CI failed, please check it out.

**Comment by aclysma** [comment]
Sorry I think I missed this. What does this fix?

**Comment by uhuntu** [comment]
Can you update to winit 0.23.0 to try ?

**Comment by Pytal** [comment]
This fix was for
```bash
cargo run --example interactive_winit_app
```

**Comment by uhuntu** [comment]
The major reason is winit from 22 to 23

**Comment by aclysma** [comment]
I see now, as a temporary measure you can use `cargo update -p winit --precise 0.22` to force using winit 0.22. Once imgui updates to work with winit - likely soon - I'm thinking about adopting their method of using feature flags to support multiple versions of winit. I don't think it's ideal to cut off 0.22 support without giving a bit of time for the ecosystem to catch up.

**Comment by uhuntu** [comment]
@Pytal as @aclysma mentioned, you should close this PR

**Comment by uhuntu** [comment]
cargo update -p winit --precise 0.22.2

**Pull request closed without merging**
