### PR TITLE
sdl2: windows has special features.

### PR DESCRIPTION
**Pull request by uhuntu**

### CODE REVIEW

**Comment by aclysma** [comment]
Not trying to be difficult, but I'd like to understand why we would remove those features from a dev-dependency? As it is right now, 
 * I'd like skulpin to build and run on all platforms with as few prerequisites as possible.
    * The only prerequisite now is installing the Vulkan SDK. Right now it's just for the debug layer but I'll probably disable it by default in the examples because I don't think it's actually helping people.
    * I know I mentioned windows as the main reason for keeping them in #60 since SDL2 is more annoying to manually install there than macOS/linux but it's still a prerequisite for those platforms and an extra step for anyone that casually wants to try skulpin out.
 * These features are not enabled for downstream crates automatically (just tried it myself). So you won't get them in your project unless you add them manually.
 * If you're modifying skulpin itself, you can easily remove them for local development.

Maybe there's a compelling reason to remove those features from being a dev-dependency but I just don't see it. Happy to reconsider if I missed something though!

**Comment by Kethku** [comment]
I second this. Enabling those features on windows makes life WAY easier

**Comment by uhuntu** [comment]
I have a comment here: https://github.com/Kethku/neovide/issues/125#issuecomment-685381975

**Comment by aclysma** [comment]
I'm suspecting you are seeing a difference in behavior because SDL2 that is being loaded statically is not the same as what's installed on your system. So this seems like an upstream issue with the sdl2 crate or SDL2 itself. If this suspicion is correct, disabling static linking here will only fix it for people who happen to have a different version of SDL2 installed - so it wouldn't be a true fix.

If you create a new binary crate and pull in skulpin via Cargo.toml, these features will not be enabled for you on any platform. I think that's the best way forward for now. Then you can manually static link against whatever version of SDL2 you need, and everyone would see the same behavior.

You may want to try installing different versions of SDL2 and build without static linking to see if some versions give different behaviors than others.

**Comment by uhuntu** [comment]
https://github.com/Rust-SDL2/rust-sdl2/pull/1025

**Comment by aclysma** [comment]
Wow, nice work tracking this one down. Thanks for sharing!

**Pull request closed without merging**
