### PR TITLE
Update skia-safe

### PR DESCRIPTION
**Pull request by Kethku**
There has been some bug fixes in skia-safe which I need for my project

### CODE REVIEW

**Comment by aclysma** [comment]
Thanks! Happy to push this through once the build finishes. I think I'd need to publish it as 0.5 since the skia API change is likely breaking.

I think there might also be a way to specify a range of compatible upstream versions. For example, it looks like this crate could work fine with 0.21, 0.22, and 0.23 of skia_safe and it's conceivable that downstream users of this crate may be on any of these versions. I think allowing a range would be more convenient if this crate were being used by more people. I need to look into exactly how cargo handles this though to know if it's a good way to go or not.

BTW I took a look at your project, super cool! And on my machine anyways it seemed very laptop-battery-friendly. (No worse than vscode)

**Comment by aclysma** [comment]
Looks like it fails on windows during curl's build.rs step. (https://github.com/alexcrichton/curl-rust/blob/master/curl-sys/build.rs)

Will have to look into it later. Ideally it'd be nice if there were some way skia_bindings could fetch the data without having to build curl. Maybe there's a missing chocolatey package on a windows build. I'm also curious as to why this hasn't been a problem before.

**Comment by Kethku** [comment]
Interesting. Not sure why that would cause problems... I can take a closer look tonight as well.

I'm glad you were able to try Neovide! Battery life is a big priority along with just general performance. Skia lets me push most of the work to the gpu which helps a ton. Do you use neovim/vim on a regular basis? If so, do you have any opinions about what a gui for it should have/not have?

**Comment by Kethku** [comment]
As for versioning, specifying a range of versions seems super preferable to me since it would enable faster updates instead of waiting for upstream pushes.

**Comment by aclysma** [comment]
I think maybe if version is ">=0.21" this might work? Do you want to give that a try?

If there is ever a breaking change, I think we would make the version be ">=0.21, <0.30" for example if 0.30 was the version that we stopped being compatible with.

I don't use vim but I still think your project is a neat idea! I think if your UI is relatively faithful to "normal" vim but with really high quality fonts and good performance, people will like it. I also like the sublime merge UI quite a bit.. they also use skia for their UI.. I think vim users would appreciate a similarly minimal UI/design language. Maybe a pretty version of nerdtree or powerline? But the approach you've taken might get you pretty good results for "free." I guess it depends on if you want it to be a minimal UI shell or if you want to sort of make your own vim-powered editor distro with extras (kind of like spacemacs), so to speak.

**Comment by Kethku** [comment]
Can't try atm. But might try later tonight

**Comment by aclysma** [comment]
Looks like this is an upstream issue: https://github.com/alexcrichton/curl-rust/issues/239

I can probably switch it to the msvc toolchain to get windows CI working again.

**Comment by aclysma** [comment]
I published two versions:
* 0.4.1: - skia-safe version is now >=0.21 and winit version is ">=0.20.0-alpha4, <0.20.0-alpha6"
    * If you use 0.4 and run cargo update, you should grab 0.4.1 and things should work fine
* 0.5.0: - winit version is 0.20.0-alpha6
    * There are some minor winit-related breaking changes you'll need to fix up, you can probably do something like this commit: https://github.com/aclysma/skulpin/commit/3e5586c68cbdb1e3ede35349961f407ca18c81cd

I confirmed for myself that this builds fine for the msvc toolchain. Maybe travis is using the gnu toolchain for some reason.

**Comment by aclysma** [comment]
Updated the travis config to explicitly use msvc for windows builds. (It's odd that it doesn't do that by default.) Looks like everything is green now!

**Pull request closed without merging**
