### PR TITLE
Bump upstream deps

### PR DESCRIPTION
**Pull request by j4qfrost**
I was playing around with some of the new features. In addition to the vulkan layers fix, this also has a fix for peek_pixel.

### CODE REVIEW

**Comment by aclysma** [comment]
You may know this already, but I generally avoid bumping the upstream dependency crate versions for ash and skia-safe as they are open-ended (i.e. ">=0.27" vs "0.27"). This works out because skulpin uses a very small amount of the API surface area and most upstream changes have been drop-in compatible. This allows end-users to choose when to update and is less disruptive for anyone that may be using this library.
 * If you sync down this library now, you will build with skia-safe 0.30.1 by default.
 * You can use `cargo update -p skia-safe --precise 0.29.3` to go to back to 0.29.3
 * Anyone with an existing Cargo.lock will keep using whatever version they had, even if upstream changes become available.

However, I noticed that the current minimum version 0.27 does not build due to a rename. (I introduced this without realizing it when fixing a deprecation warning). So I could either:
 * Undo the change to keep compatibility back to 0.27 (would also disable the deprecation warning)
 * Bump to 0.29
 * Bump to 0.30. Since there was an issue with 0.30, I'd go ahead and bump to 0.30.1 as you have done in this change.

Do you have an opinion on this? I'm happy to go with whatever suits neovide since to my knowledge it's the largest user of this library. Currently neovide is on 0.27.

**Comment by Kethku** [comment]
Id say do whatever makes sense for skulpin. We can make neovide work with w/e and I don't want us to be a burden on your architecture or versioning decisions

**Comment by j4qfrost** [comment]
I second @Kethku 's comment. I was a bit overzealous about that particular feature change. Though version 0.31.1 does allow for some debugging features such as dumping snapshots of images, which might be a useful utility function. I had some issues when trying to access the textures https://github.com/rust-skia/rust-skia/issues/355

**Comment by aclysma** [comment]
Sorry I forgot about this! Lets go ahead and do it, we can consider reverting if it ends up causing unpleasantness for someone.

**Pull request merged**
